// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9f4fbe5a-c9a4-409e-a946-13c28da7fa61",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rylPYkvnC",
    "aws_user_pools_web_client_id": "40e4mc3um8ss0ruitds66msq5b",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://cjglddadubfubkvh5iar6y4vvy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
